import pandas as pd
from catboost import CatBoostRegressor

# Load the dataset generated by your Java code
df = pd.read_csv("rounds_remaining.csv")

# Define features (must match your rlFeatures list) and target
# Get feature names from all columns except the last one
feature_names = list(df.columns[:-1])
target_name = df.columns[-1] # Should be 'rounds_left'

X = df[feature_names]
y = df[target_name]

# Initialize and train the CatBoost Regressor
# You can tune these parameters
model = CatBoostRegressor(iterations=500,
                          learning_rate=0.1,
                          depth=6,
                          loss_function='RMSE')

model.fit(X, y, verbose=100)

# Save the model in CatBoost's binary format
model.save_model("rounds_left_model.cbm")
print("Model saved as rounds_left_model.cbm")